development:
  server:
    port: 3002
    host: localhost
  bots:
    - johnny5:
      campfire:
        config:
          token: "ea9f77add0b6ba0aa54e79d7c1111aabbf9aec01"
          account: niuage
          ssl: 1
        rooms:
          - id: 169602
          - id: 392773
          - id: 392800
      engines:
        - name: J5
        - name: Flickr
        - name: Weather
        - name: Tmdb
        - name: Bitly
        - name: Wolfram
        - name: Github
    - niuage:
      campfire:
        config:
          token: "7f3e8b9c4caff6db3ac20d7afe93c88c59e17736"
          account: challengepost
          ssl: 1
        rooms:
          - id: 348877
          - id: 360348
          - id: 273935
          - id: 357538
      engines:
        - name: J5
        - name: Flickr
        - name: Weather
        - name: Tmdb
        - name: Bitly
        - name: Wolfram
        - name: Github
  engines:
    - J5:
      api:
        key: ""
    - Flickr:
      api:
        key: "2bc972efba6309fe9376d55482ab32bb"
    - Weather:
      api:
        key: "c5289d5b3b5fd943"
        secret: 1245671229
      default_location: 10014
    - Tmdb:
      api:
        key: "0feeb53d4f29c916ce155789b1cfda00"
    - Bitly:
      api:
        key: "R_c5731eaf90d0abfbda2c226e356a70c7"
        secret: niuage2
    - Wolfram:
      api:
        key: "T58EKE-35TP7JWUQY"
        secret: Johnny5
    - Github:
      api:
        key: "9f9301887a2846ad42c2ad751cff15aa"
        secret: niuage
